services:
  server:
    image: tiberiuam/actions-test
    container_name: node-server
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    depends_on:
      - server